### PR TITLE
Gracefully handle files that are not from a theme

### LINKED ISSUE #973: findThemeRoot should throw or return undefined when it can't find one
**Describe the bug**
I think findThemeRootURI assumes that it will always find a root. That's not true. Say you are in your theme and you take a look at your vscode's settings.json file, you won't be able to find the theme root from that URI. 

That assumption is wrong and is unfortunately used everywhere in the stack. 

We probably should change the return type of `findThemeRootURI` to possibly return `undefined` when it can't find a root.

Then we'll need to adjust all the call sites and add handling for when that happens. Usually that means returning early, returning no results, etc. 

It's too big of a task to include in #956 

That kind of assumption is what causes the dependency graph to load 4000 files when the focused file is settings.json in $HOME/Library/...

### PR DESCRIPTION
**Pull request by charlespwd**
Make findThemeRootURI return null when it can't find a root

Make everywhere handle null when no root is found

Should fix "preloading" of theme when looking at `$HOME/Library/Application Support/Code/User/settings.json`

Also, `snippets` can be found in `$HOME/Library/Application Support/Code/User` and is a VS Code-owned, non theme thing. So had to modify the findRoot algo to search for assets _and_ snippets folder existence.

Fixes #973

## Before you deploy

- [x] I included a patch bump `changeset`

### CODE REVIEW

File: packages/theme-check-common/src/checks/valid-visible-if/visible-if-utils.ts [hunk 1]
```diff
@@ -140,11 +133,8 @@ export async function getGlobalSettings(context: Context<SourceCodeType>) {
   const globalSettings: string[] = [];
 
   try {
-    const path = join(
-      await findRoot(context.file.uri, context.fileExists),
-      'config/settings_schema.json',
-    );
-    const settingsFile = await context.fs.readFile(path);
```
Comment (charlespwd) [inline packages/theme-check-common/src/checks/valid-visible-if/visible-if-utils.ts:147]: toURI does this better.

File: packages/theme-check-common/src/test/MockFileSystem.ts [hunk 2]
```diff
@@ -46,32 +48,37 @@ export class MockFileSystem implements AbstractFileSystem {
...
+      let current = result;
+      for (let i = 0; i < segments.length - 1; i++) {
+        const segment = segments[i];
+        current[segment] ??= {};
+        current = current[segment] as FileTree;
       }
+      current[segments[segments.length - 1]] = source;
     }
-    return this._fileTree;
+    return result;
```
Comment (charlespwd) [inline packages/theme-check-common/src/test/MockFileSystem.ts:81]: Had to remove memoization because of a test that mutated this.mockTheme. It's only for tests, perf doesn't matter :)

File: packages/theme-language-server-common/src/diagnostics/runChecks.ts [hunk 3]
```diff
@@ -43,7 +43,7 @@ export function makeRunChecks(
     // then we recheck theme1
     const fileExists = makeFileExists(fs);
     const rootURIs = await Promise.all(triggerURIs.map((uri) => findRoot(uri, fileExists)));
-    const deduplicatedRootURIs = new Set(rootURIs);
+    const deduplicatedRootURIs = new Set<string>(rootURIs.filter((x): x is string => !!x));
     await Promise.all([...deduplicatedRootURIs].map(runChecksForRoot));
```
Comment (charlespwd) [inline packages/theme-language-server-common/src/diagnostics/runChecks.ts:47]: Impact: runChecks won't run when triggered from a file that you can't find a root for.

File: packages/theme-language-server-common/src/documentLinks/DocumentLinksProvider.ts [hunk 4]
```diff
@@ -24,6 +25,10 @@ export class DocumentLinksProvider {
     }
 
     const rootUri = await this.findThemeRootURI(uriString);
+    if (!rootUri) {
+      return [];
+    }
+
```
Comment (charlespwd) [inline packages/theme-language-server-common/src/documentLinks/DocumentLinksProvider.ts:31]: No document links when you can't find a root.

File: packages/theme-language-server-common/src/rename/providers/LiquidVariableRenameProvider.ts [hunk 5]
```diff
@@ -71,7 +72,7 @@ export class LiquidVariableRenameProvider implements BaseRenameProvider {
     const rootUri = await this.findThemeRootURI(params.textDocument.uri);
     const textDocument = document?.textDocument;
 
-    if (!textDocument || !node || !ancestors) return null;
+    if (!rootUri || !textDocument || !node || !ancestors) return null;
```
Comment (charlespwd) [inline packages/theme-language-server-common/src/rename/providers/LiquidVariableRenameProvider.ts:75]: No variable rename when you can't find a root.

File: packages/theme-language-server-common/src/renamed/handlers/AssetRenameHandler.ts [hunk 6]
```diff
@@ -44,6 +45,7 @@ export class AssetRenameHandler implements BaseRenameHandler {
     if (relevantRenames.length !== 1) return;
     const rename = relevantRenames[0];
     const rootUri = await this.findThemeRootURI(path.dirname(params.files[0].oldUri));
+    if (!rootUri) return;
```
Comment (charlespwd) [inline packages/theme-language-server-common/src/renamed/handlers/AssetRenameHandler.ts:48]: No asset rename when you can't find a root

File: packages/theme-language-server-common/src/server/ThemeGraphManager.ts [hunk 7]
```diff
@@ -33,11 +34,15 @@ export class ThemeGraphManager {
...
     private documentManager: DocumentManager,
     private fs: AbstractFileSystem,
-    private findThemeRootURI: (uri: string) => Promise<string>,
+    private findThemeRootURI: FindThemeRootURI,
   ) {}
 
   async getThemeGraphForURI(uri: string) {
     const rootUri = await this.findThemeRootURI(uri);
+    if (!rootUri) {
+      return undefined;
```
Comment (charlespwd) [inline packages/theme-language-server-common/src/server/ThemeGraphManager.ts:43]: No theme graph for files that are not part of a theme

File: packages/theme-language-server-common/src/server/startServer.spec.ts [hunk 8]
```diff
@@ -58,7 +58,7 @@ describe('Module: server', () => {
       }
     });
 
-    fileTree = { 'snippets/code.liquid': fileContents };
+    fileTree = { '.theme-check.yml': '', 'snippets/code.liquid': fileContents };
```
Comment (charlespwd) [inline packages/theme-language-server-common/src/server/startServer.spec.ts:61]: Since `Application Support/Code/User/snippets` exists and since `Application Suport/Code/User/settings.json` is a file you're likely to edit, we were inferring `Application Support/Code/User` to be the root of a theme. That was not very good. So I changed the algo to look for `snippets` _and_ `assets` (as well as looking for `.theme-chekc.yml`).

For the unit tests, it was easiest to simply put a `.theme-check.yml`

File: packages/theme-language-server-common/src/server/startServer.ts [hunk 9]
```diff
@@ -158,8 +160,13 @@ export function startServer(
...
   );
 
-  const getMetafieldDefinitions = async (uri: string) => {
+  const getMetafieldDefinitions: NonNullable<Dependencies['getMetafieldDefinitions']> = async (
+    uri: string,
+  ) => {
     const rootUri = await findThemeRootURI(uri);
+    if (!rootUri) {
+      return {} as MetafieldDefinitionMap;
+    }
```
Comment (charlespwd) [inline packages/theme-language-server-common/src/server/startServer.ts:169]: no root URI means no `.shopify` folder gets generated in non-themes.

File: packages/theme-check-common/src/find-root.ts [hunk 10]
```diff
@@ -7,12 +7,19 @@ async function isRoot(dir: UriString, fileExists: FileExists) {
...
     fileExists(path.join(dir, '.theme-check.yml')),
-    fileExists(path.join(dir, '.git')),
 
-    // zip files and TAEs might not have config files, but they should have a
-    // snippets directory but in case they do specify a .theme-check.yml a
+    // Maybe the root of the workspace has an assets + snippets directory, we'll accept that
+    and(
+      fileExists(path.join(dir, '.git')),
+      fileExists(path.join(dir, 'assets')),
+      fileExists(path.join(dir, 'shippets')),
```
Comment (aswamy) [inline packages/theme-check-common/src/find-root.ts]: `shippets`? 😅

File: packages/theme-language-server-common/src/server/startServer.ts (hunk 9 above)
Comment (aswamy) [reply packages/theme-language-server-common/src/server/startServer.ts:169]: Metafields file never got created on my system but i feel like it's a problem outside of the rootUri... can you check yours to see if it's working. It's failing on the `exec` function in `packages/theme-language-server-node/src/metafieldDefinitions.ts` line 46.

File: packages/theme-check-common/src/find-root.ts (hunk 10 above)
Comment (charlespwd) [reply packages/theme-check-common/src/find-root.ts]: oh god

File: packages/theme-language-server-common/src/server/startServer.ts (hunk 9 above)
Comment (charlespwd) [reply packages/theme-language-server-common/src/server/startServer.ts:169]: They load fine for me 🤔
